### ISSUE TITLE
Search filters not working

### ISSUE THREAD

**Issue by tamagokun** [acumenbrands/rest_suite#22]
It seems that the operator isn't getting passed in when create the search filter object:

https://github.com/acumenbrands/rest_suite/blob/master/lib/netsuite_toolkit.js#L177-L179

Receiving this error:

```json
"result" : {
    "params" : null,
    "result" : null,
    "success" : false,
    "exception" : {
      "trace" : [
        "restletwrapper(null$lib:4)"
      ],
      "message" : "An nlobjSearchFilter contains an invalid operator, or is not in proper syntax: internalidnumber."
    }
  },
```

Even if I pass the operator in to seemingly properly create the filter, it fails.

For some context, i'm using the following request body:

```json
{
  "record_type": "customer",
  "search_filters": [
    {
      "name": "email",
      "operator": "is",
      "value": "....@...com"
    }
  ]
}
```

**Comment by tamagokun** [comment]
The lowBound filter seemed to be the culprit here. I just prevented that filter getting added to the filters array, and my search worked.

**Comment by hayden-t** [comment]
Hey , This needs opening up again, there are problems with that lowerbound function i will look into. it still has issues ... you still there ?

**Comment by tamagokun** [comment]
@hayden-t it's been so long, I don't honestly remember what I did to fix this, but here's the major difference:

https://github.com/acumenbrands/rest_suite/blob/master/lib/search.js#L140
`searchFilterData[this.SEARCH_FILTER_NAME_KEY]     = 'internalid';`

There were a couple other things I added to improve how I could search, but I don't remember why I did that!

**Comment by hayden-t** [comment]
I worked it out, i had created the problem, but i fixed it. while ive got you, do you know how to use the search formula feature ?
